name: dependency-check
on:
    workflow_call:

jobs:
    dependency-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                 python-version: '3.13'

            - name: Pip Dependency Check
              run: pip install pip-audit

            - name: Audit Dependencies
              run: pip-audit -r requirements.txt