name: Secrets-Scan
on:
    workflow_call:
jobs:
    secrets-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run Git Leaks Scanner
              uses: gitleaks/gitleaks-action@v2
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}